"""Build static HTML from the canonical inventory. Python standard library only."""
from pathlib import Path
import json,html,re
from seo import metadata as seo_metadata
R=Path(__file__).resolve().parents[1];data=json.loads((R/'data/inventory.json').read_text());E=html.escape
works=data['works'];shelf_works=[w for w in works if w.get('showInShelf',True)];colors=['#c0b78a','#b56645','#e3d8bb','#aaa990','#9b654e','#b9ac95','#a1a896','#cab37d']
def cover(w,cls=''):
 if w['cover']:return f'<img class="{cls}" src="{E(w["cover"])}" alt="{E(w.get("coverAlt", "Cubierta de " + w["title"]))}" loading="lazy" width="{w.get("coverWidth",360)}" height="{w.get("coverHeight",540)}">'
 return f'<div class="type-cover {cls}" aria-label="{E(w["title"])}"><small>FERNANDO ARIZA</small><strong>{E(w["title"])}</strong><span>{E(w["publisher"])} · {w["year"]}</span></div>'
def metadata(w):
 return f'<p class="role">{E(w["role"])}</p><p>{E(w["description"])}</p><dl><div><dt>Editorial</dt><dd>{E(w["publisher"])}</dd></div><div><dt>Año</dt><dd>{w["year"]}</dd></div>'+ (f'<div><dt>ISBN</dt><dd>{w["isbn"]}</dd></div>' if w['isbn'] else '')+(f'<div><dt>Páginas</dt><dd>{w["pages"]}</dd></div>' if w['pages'] else '')+f'</dl><a class="text-link" href="{E(w["sources"][0]["url"])}" target="_blank" rel="noopener noreferrer">Consultar la publicación <span aria-hidden="true">↗</span></a>'
shelf=''
for i,w in enumerate(shelf_works):
 shelf+=f'''<article class="book {'is-open' if i==0 else ''}" data-id="{w['id']}" data-category="{E(w['category'])}" style="--book-color:{colors[i%len(colors)]}"><button class="spine" aria-expanded="{'true' if i==0 else 'false'}" aria-controls="panel-{w['id']}" id="spine-{w['id']}"><span class="spine-number">{i+1:02}</span><span class="spine-title">{E(w['title'])}</span><span class="spine-year">{w['year']}</span><span class="spine-plus" aria-hidden="true">↗</span></button><div class="book-panel" id="panel-{w['id']}" role="region" aria-labelledby="spine-{w['id']}" {'hidden' if i else ''}><div class="cover-wrap">{cover(w)}</div><div class="book-copy"><span class="eyebrow">{E(w['category'])} / {w['year']}</span><h3>{E(w['title'])}</h3>{metadata(w)}</div></div></article>'''
index=''
for w in sorted(works,key=lambda w:-w['year']):
 shelf_link=f'<a class="text-link shelf-jump" href="#libro-{w["id"]}">Ver en la biblioteca ↗</a>' if w.get('showInShelf',True) else ''
 index+=f'<details class="index-row" id="obra-{w["id"]}" data-category="{E(w["category"])}" data-search="{E((w["title"]+" "+w["category"]+" "+w["publisher"]).lower())}"><summary><time>{w["year"]}</time><h3>{E(w["title"])}</h3><span class="row-category">{E(w["category"])}</span><span class="row-arrow" aria-hidden="true">+</span></summary><div class="index-detail">{cover(w)}<div>{metadata(w)}{shelf_link}</div></div></details>'
academic=''
for a in data['academicRecords']:
 if a['category'] not in ['Artículos de revistas','Colaboraciones en obras colectivas','Reseñas']:continue
 academic+=f'<article class="academic-row"><div><span class="eyebrow">{E(a["category"])}</span><h3><a href="{E(a["url"])}" target="_blank" rel="noopener noreferrer">{E(a["title"])} ↗</a></h3><p>{E(a["citation"])}</p></div></article>'
months=['ene','feb','mar','abr','may','jun','jul','ago','sep','oct','nov','dic']
articles=sorted(data['articles'],key=lambda a:(a['date'],a['title']),reverse=True)
def article_row(a,archive=False):
 year,month,day=a['date'].split('-')
 reason=f'<p class="selection-reason">{E(a["selectionReason"])}</p>' if not archive else ''
 search=E((a['title']+' '+a['publication']+' '+a['date']+' '+months[int(month)-1]).lower())
 return f'<a class="press-row {"archive-row" if archive else "selected-article"}" data-date="{a["date"]}" data-publication="{E(a["publication"])}" data-search="{search}" href="{E(a["url"])}" target="_blank" rel="noopener noreferrer"><span class="publication">{E(a["publication"])}</span><div class="article-copy"><h3>{E(a["title"])}</h3>{reason}</div><span class="article-date"><time datetime="{a["date"]}"><strong>{year}</strong><span>{int(day):02} {months[int(month)-1]}</span></time><span aria-hidden="true">↗</span></span></a>'
press=''.join(article_row(a) for a in articles if a.get('featured'))
press_archive=''.join(article_row(a,True) for a in articles)
publication_options=''.join(f'<option value="{E(pub)}">{E(pub)}</option>' for pub in sorted({a['publication'] for a in articles}))
reviews='' 
for i,q in enumerate(data['reviews']):
 portrait=f'<img src="{q["portrait"]}" width="48" height="48" loading="lazy" alt="">' if q['portrait'] else '<span class="review-initials" aria-hidden="true">AP</span>'
 reviews+=f'<article class="review-card" tabindex="0" aria-label="Reseña de {E(q["name"])}" style="--card-index:{i}"><span class="eyebrow">{i+1:02} / Lecturas de la obra</span><blockquote>«{E(q["quote"])}»</blockquote><div class="review-author">{portrait}<div><strong>{E(q["name"])}</strong><span>{E(q["publication"])}</span></div></div></article>'
options=''.join(f'<option>{E(c)}</option>' for c in dict.fromkeys(w['category'] for w in works))
shelf_options=''.join(f'<option>{E(c)}</option>' for c in dict.fromkeys(w['category'] for w in shelf_works))
featured=''
for w in works[:2]:featured+=f'<a class="featured-book" href="#libro-{w["id"]}"><div class="featured-image">{cover(w)}</div><div><span class="eyebrow">Novela / {w["year"]}</span><h3>{E(w["title"])} <span>↗</span></h3></div></a>'
body=f'''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Fernando Ariza — Literatura, ensayo y crítica</title><meta name="description" content="La obra de Fernando Ariza: novelas, biografías, ensayo, ediciones y crítica literaria."><meta name="robots" content="noindex,follow"><meta name="theme-color" content="#ede7d7">{seo_metadata(data)}<link rel="stylesheet" href="style.css"><script src="app.js" defer></script></head><body>
<a class="skip" href="#contenido">Saltar al contenido</a><header class="header"><a class="wordmark" href="#inicio">Fernando Ariza<span>Escritor & profesor</span></a><nav aria-label="Principal"><a href="#biblioteca">Obra</a><a href="#lecturas">Crítica</a><a href="#autor">El autor</a><a href="#contacto">Contacto <span aria-hidden="true">↗</span></a></nav></header>
<main id="contenido"><section class="hero" id="inicio" aria-labelledby="hero-title"><div class="hero-meta"><span>Madrid, 1978</span><span>Novela · Ensayo · Crítica literaria</span><span class="edition">Una vida entre libros</span></div><h1 id="hero-title"><span class="hero-line">Fernando</span><span class="hero-line second">Ariza<span class="hero-asterisk" aria-hidden="true">✳</span></span></h1><div class="hero-bottom"><span class="eyebrow">Escribir. Leer. Pensar.</span><p>Escritor, crítico literario y profesor de Literatura en la Universidad CEU San Pablo.</p><a href="#seleccion" class="circle-link" aria-label="Descubrir la obra">↓</a></div><div class="hero-picture"><img src="images/ciudad-dormida-background-hero.webp" width="1600" height="900" alt="" fetchpriority="high"><span>La literatura, una forma de mirar.</span></div></section>
<section class="section selected" id="seleccion"><div class="section-top"><span class="eyebrow">01 / Narrativa</span><span>Dos novelas, dos mundos</span></div><div class="selected-layout"><div class="selected-heading"><h2>Historias <br>que nos <br><em>atañen.</em></h2><p>De una ciudad que guarda sus secretos a una pareja que busca empezar de nuevo.</p><a class="text-link" href="#biblioteca">Explorar toda la obra ↗</a></div><div class="featured">{featured}</div></div></section>
<div class="moving-type" aria-hidden="true"><span>Leer el mundo. Escribir la vida.</span></div>
<section class="library section" id="biblioteca"><div class="section-top"><span class="eyebrow">02 / La biblioteca</span><a class="text-link" href="#indice">Ir al índice ↓</a></div><div class="title-row"><h2>Entre libros<span class="sup">{len(shelf_works):02}</span></h2><p>Novelas, ensayo, investigación y otras formas de acercarse a la literatura.</p></div><div class="library-tools"><label>Explorar por <select id="shelf-category"><option value="all">Toda la selección</option>{shelf_options}</select></label><span class="shelf-hint">Selecciona un lomo para abrir un libro</span><div class="shelf-arrows"><button id="previous-book" aria-label="Libro anterior">←</button><button id="next-book" aria-label="Libro siguiente">→</button></div></div><div class="bookshelf">{shelf}</div><p class="shelf-status" aria-live="polite"></p></section>
<section class="section index-section" id="indice"><div class="section-top"><span class="eyebrow">03 / Índice de obra</span><span>2004 — 2026</span></div><div class="title-row"><h2>Obra, por año.</h2><p>Otra manera de recorrer la biblioteca: abre cada título para consultar su ficha.</p></div><div class="index-tools"><label class="search-label">Buscar una obra<input id="work-search" type="search" placeholder="Título, editorial o categoría…"></label><label>Categoría<select id="index-category"><option value="all">Todas</option>{options}</select></label><p id="result-count" aria-live="polite">{len(works)} obras</p></div><div id="work-index">{index}</div><p id="no-results" hidden>No hay obras que coincidan. Prueba con otro título o categoría.</p><details class="academic"><summary><span>Artículos y capítulos de investigación</span><span>{len([a for a in data['academicRecords'] if a['category'] in ['Artículos de revistas','Colaboraciones en obras colectivas','Reseñas']])} referencias +</span></summary><div class="academic-intro"><p>Artículos académicos, capítulos y reseñas bibliográficas. Cada referencia enlaza con su registro documental.</p><a class="text-link" href="https://dialnet.unirioja.es/servlet/autor?codigo=887454" target="_blank" rel="noopener noreferrer">Consultar Dialnet ↗</a></div>{academic}</details></section>
<section class="section criticism" id="lecturas"><div class="section-top"><span class="eyebrow">04 / Crítica literaria</span><span>Artículos, reseñas y conversaciones</span></div><div class="title-row"><h2>Al otro lado<br><em>de la página.</em></h2><p>Seis lecturas escogidas por su relación con sus novelas, su investigación editorial y su mirada sobre el oficio de escribir.</p></div><p class="selection-label eyebrow">Lecturas escogidas · seis puertas de entrada</p>{press}<div class="press-links"><a class="text-link" href="https://www.eldebate.com/autor/fernando-ariza/" target="_blank" rel="noopener noreferrer">Todos los artículos en El Debate ↗</a><a class="text-link" href="https://www.zendalibros.com/author/fernandoariza/" target="_blank" rel="noopener noreferrer">Todas las lecturas en Zenda ↗</a></div><details class="press-archive"><summary>Explorar el archivo de artículos <span>{len(data["articles"])} referencias +</span></summary><p class="archive-intro">Del más reciente al más antiguo, con independencia de la publicación.</p><div class="archive-controls"><label class="archive-search-label">Buscar en el archivo<input id="press-search" type="search" placeholder="Título, publicación o fecha…"></label><label class="publication-filter">Publicación<select id="press-publication"><option value="all">Todas las publicaciones</option>{publication_options}</select></label></div><p id="press-count" aria-live="polite">{len(articles)} artículos</p><p id="press-empty" hidden>No hay artículos que coincidan con esta búsqueda.</p>{press_archive}</details></section>
<section class="section reception" id="resenas"><div class="section-top"><span class="eyebrow">05 / La mirada de otros</span><span>Reseñas de su obra</span></div><h2>En otras palabras.</h2><p class="review-hint">Selecciona una tarjeta para leerla.</p><div class="review-stack">{reviews}</div></section>
<section class="section author" id="autor"><div class="section-top"><span class="eyebrow">06 / El autor</span><span>Fernando Ariza</span></div><div class="author-layout"><div class="portrait"><img src="images/fernando.webp" width="360" height="440" loading="lazy" alt="Fernando Ariza"><span>Madrid, 1978</span></div><div><h2>Una vida<br>entre <em>libros.</em></h2><p class="author-lead">Novelista, investigador, profesor y crítico literario.</p><p>Doctor en Filología Hispánica por la Universidad Complutense de Madrid y máster en Edición por la Universidad de Salamanca. Es profesor de Literatura en la Universidad CEU San Pablo.</p><p>Su trabajo reúne creación narrativa, historia editorial y estudio de la literatura. Es autor de las novelas <em>Ciudad dormida</em> y <em>Fuiste el rey</em>, y de biografías, ensayos y guías de lectura.</p><p>Colabora como crítico en Zenda y en El Debate, donde es responsable de la sección de libros.</p><p>Ha sido invitado a universidades estadounidenses como Columbia, Nueva York y Austin. Se inició en la ficción con las biografías noveladas de Bécquer y Valle-Inclán.</p><p>Fuera de la escritura y la docencia, disfruta de los libros de cocina y de cuidar plantas de interior.</p><div class="author-links"><a class="text-link" href="#indice">Recorrer su obra ↓</a><a class="text-link" href="https://x.com/ferariza_" target="_blank" rel="me noopener noreferrer">Fernando en X ↗</a></div></div></div></section>
<footer class="section contact" id="contacto"><div class="section-top"><span class="eyebrow">07 / Contacto</span><a href="#inicio">Volver arriba ↑</a></div><h2>Seguimos<br><em>conversando.</em></h2><a class="email" href="mailto:ferariza@ferariza.com">ferariza@ferariza.com <span>↗</span></a><div class="footer-bottom"><span>© Fernando Ariza</span><span>Literatura · Investigación · Docencia</span><a href="#inicio">Volver al inicio ↑</a></div></footer></main><noscript><p class="noscript-note">Puedes consultar toda la obra y abrir sus fichas en el índice. La biblioteca interactiva requiere JavaScript.</p></noscript></body></html>'''
(R/'index.html').write_text(body)
print('Built',R/'index.html')
